# Copyright (C) 2026 RM4 LLC
# SPDX-License-Identifier: GPL-3.0-or-later

FROM quay.io/podman/stable:latest
# Rootless podman and mapping user IDs is a nightmare. Container start may take hours during chowns to map users.
# We will run as root as the expectation is a rootless container.
USER 0
# We will use nix for user package management.
RUN dnf -y update \
    && dnf -y install nix man-pages procps --exclude nix-daemon \
    && dnf clean all \
    && rm -rf /var/cache /var/log/dnf* /var/log/hawkey.log /var/log/yum.*
COPY src/nix /var/rm4dev/nix
RUN --mount=type=cache,id=rm4dev-nix,target=/nix \
    nix --extra-experimental-features "nix-command flakes" profile add /var/rm4dev/nix
RUN --mount=type=cache,id=rm4dev-nix,target=/nix-cache \
    cp -a /nix-cache/. /nix/
RUN nix profile upgrade rm4dev-devtools
# Still use rustup for Rust management.
RUN /bin/bash -lc 'rustup default stable'
# Still want a nice entrypoint script for simple modification and usage.
COPY src/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
WORKDIR /work
COPY src/AGENTS.md /work/AGENTS.md
COPY src/skills /work/.agents/skills
ENV RM4_BASE_DIR=/work/rm4
# Login shell for entrypoint.
ENTRYPOINT ["/bin/bash"]
CMD ["-lc", "/entrypoint.sh"]
